### PR TITLE
xsbt-web-plugin 1.0 upgrade

### PR DESCRIPTION
**Pull request by seratch**
refs #9 

This pull request is based on @dozed's work and his fix basically seems to be fine. Good job! :+1: 

Additionally I've fixed other things as below.

- publish to sonatype repo from scalasbt.artifactoryonline.com (no problem?)
- remove unnecessary `project/builld.scala`
- apply scalariform's code formatter

Furthermore, I just tried this version with xsbt-web-plugin 1.1.0 and it worked fine too (I didn't do upgrade in this PR yet).

This branch has been published to sonatype snapshot repository. If you're interested in, try it out and give us your feedback. 
https://oss.sonatype.org/content/repositories/snapshots/org/scalatra/sbt/scalatra-sbt_2.10_0.13/0.4.0-SNAPSHOT/

Thanks in advance.

### CODE REVIEW

**Comment by seratch** [comment]
To @rossabaker, @dozed and all the collaborators of this project,

 I found I don't have a permission to merge pull requests on this project (scalatra-sbt). If no problem, please consider adding me to project collaborators.

**Comment by dozed** [comment]
@seratch Thanks for putting the PR together. I cant manage permissions on the repository, maybe @casualjim ?

**Comment by rossabaker** [comment]
I added the committers team from the main repo to this repo, so you can both merge in the future.

**Comment by seratch** [comment]
@rossabaker Thanks!

**Pull request merged**
